### PR TITLE
fix: regex to match html5 file name in local COM

### PR DESCRIPTION
**Pull request by ShuguangSun**
**Summary**
As issue https://github.com/sassoftware/vscode-sas-extension/issues/346, if I use a local of zh_CN, then there is no space after 'HTML5 Body', the regex can't match this line and can't find the output html filename.

For example,
```
NOTE: ����д�� HTML5 Body�����壩�ļ�: sashtml.htm
```

**Testing**
I test it in 
- SAS 9.4M7 from OA
- vscode 1.79.2
- using local COM

### CODE REVIEW

**Comment by smorrisj** [comment]
@ShuguangSun looks pretty good. Can you possibly add a covering unit test That verifies that the zh_CN format also works?

**Review by smorrisj — COMMENTED** [review]
Can you add a covering unit test?

**Comment by ShuguangSun** [comment]
I have no experience to write ts test and tried. Please review.

**Comment by ShuguangSun** [comment]
Sorry. I just make the pull request dirty. Would try to fix it.

**Comment by ShuguangSun** [comment]
The change is from
```
line.match(/NOTE: .+ HTML5.* Body .+: (.+)\.htm/)?.[1] ??
```
to
```
line.match(/NOTE: .+ HTML5.* Body.+: (.+)\.htm/)?.[1] ??
```

**Pull request closed without merging**
