### PR TITLE
chore: add translations for 1.10.0

### PR DESCRIPTION
**Pull request by scottdover**
**Summary**
This updates the translations needed for our 1.10.0 release.  There are two ways to update translations.
 - You can add suggestions for each translated string. [click here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request) for more information on adding suggestions.
 - You can update translations using one of the csvs below by editing the file and re-attaching it to this pull request
        - **de**: [de-locale-update-1.10.0.csv](https://github.com/user-attachments/files/15514479/de-locale-update-1.10.0.csv)
        - **es**: [es-locale-update-1.10.0.csv](https://github.com/user-attachments/files/15514480/es-locale-update-1.10.0.csv)
        - **fr**: [fr-locale-update-1.10.0.csv](https://github.com/user-attachments/files/15514481/fr-locale-update-1.10.0.csv)
        - **it**: [it-locale-update-1.10.0.csv](https://github.com/user-attachments/files/15514482/it-locale-update-1.10.0.csv)
        - **ja**: [ja-locale-update-1.10.0.csv](https://github.com/user-attachments/files/15514483/ja-locale-update-1.10.0.csv)
        - **ko**: [ko-locale-update-1.10.0.csv](https://github.com/user-attachments/files/15514484/ko-locale-update-1.10.0.csv)
        - **pt-br**: [pt-br-locale-update-1.10.0.csv](https://github.com/user-attachments/files/15514485/pt-br-locale-update-1.10.0.csv)

**Testing**
 - [x] Verify **de** strings are translated
 - [x] Verify **es** strings are translated
 - [x] Verify **fr** strings are translated
 - [x] Verify **ja** strings are translated
 - [x] Verify **ko** strings are translated
 - [x] Verify **zh-cn** strings are translated
 - [x] Verify **it** strings are translated
 - [x] Verify **pt-br** strings are translated
 - [x] Verify all strings are captured by running the translation check (see https://github.com/sassoftware/vscode-sas-extension/actions/runs/9516718487)

### CODE REVIEW

**Comment by Criptic** [comment]
[de-locale-update-1.10.0.csv](https://github.com/user-attachments/files/15515079/de-locale-update-1.10.0.csv)

**Comment by SASJedi** [comment]
pt-br-locale-update-1.10.0.csv updated
[pt-br-locale-update-1.10.0.csv](https://github.com/user-attachments/files/15538067/pt-br-locale-update-1.10.0.csv)

**Comment by dfxvir** [comment]
[fr-locale-update-1.10.0.csv](https://github.com/user-attachments/files/15551812/fr-locale-update-1.10.0.csv)

**Comment by meilanji** [comment]
ko-locale-update-1.10.0.csv updated
[ko-locale-update-1.10.0.csv](https://github.com/user-attachments/files/15830456/ko-locale-update-1.10.0.csv)

**Review by smorrisj — APPROVED** [review]

**Pull request merged**
