### PR TITLE
Add German language support

### PR DESCRIPTION
**Pull request by Criptic**
**Summary**
Duplicated the package.nls.json to package.nls.de.json, in accordance with https://code.visualstudio.com/docs/getstarted/locales#_available-locales, and translated the text first by hand and then rechecking my translation and refining them using deepl

**Testing**
How did you test this change? I ran npm install and then hit F5 and started to click around in the UI to find things that looked out of place to me.
Findings: While looking around in the application I realized that when SAS is starting a session you get a small pop-up in the right hand corner displaying the text: Connecting to SAS session... - I was unable to identify this text in the language file
[ContributorAgreementSASVSCode.txt](https://github.com/sassoftware/vscode-sas-extension/files/12405660/ContributorAgreementSASVSCode.txt)

### CODE REVIEW

**Comment by scnwwu** [comment]
Hi, in addition to the `package.nls.json` file, there's another translation file
https://github.com/sassoftware/vscode-sas-extension/blob/main/l10n/bundle.l10n.zh-cn.json
You'll find "Connecting to SAS session..." there:)

**Comment by Criptic** [comment]
@scnwwu  thanks for the note - will add the translation for that as well - I wasn't aware that I had to add the translations in more then one place!

**Comment by scottdover** [comment]
Hey @Criptic. Since you're working on translating the extension to German, do you mind taking a look at https://github.com/sassoftware/vscode-sas-extension/pull/464/files and making sure the notes in `CONTRIBUTING.md` make sense?

**Comment by Criptic** [comment]
Hey @scottdover they make sense to me.

**Review by scnwwu — APPROVED** [review]

**Comment by scnwwu** [comment]
Thanks for the contribution!

**Comment by liu-lihua** [comment]
I chcked the resource bundle in master branch bundle.l10n.de.json and verified it in VSCE. German could be displayed successfully. So I add "ready for release" label so that this PR could be delievered in 1.3.0.

**Pull request merged**
