### PR TITLE
feat: enable find in result pane

### LINKED ISSUE #700: Search in Result pane
Hi, when I run local sas 9 code in vscode using the extension, l cannot use search (ctrl+f or edit>find) to search the contents of the Result pane.

To replicate: run proc contents on a dataset, then try to search through the variables table in the Result pane - there isn't any search function.

Are there any workarounds or is this something the extension could support in the future? Thanks!

### PR DESCRIPTION
**Pull request by scnwwu**
**Summary**
Resolve #700

**Testing**

1. Run code to get HTML result
2. Focus in the Result pane
3. Press the find shortcut (by default Ctrl+F on Windows)

### CODE REVIEW

**Review by scottdover — APPROVED** [review]

**Comment by Zhirong2022** [comment]
VSC will quit in certain case
1. Run some SAS code
2. Ctrl+f to open Find control
3. Type something in find input box and perform search, then keep Find control on the page 
4. Click other tab page
5. Click result tab page, VSC will quit unexpectedly

**Comment by scnwwu** [comment]
> VSC will quit in certain case
> 
> 1. Run some SAS code
> 2. Ctrl+f to open Find control
> 3. Type something in find input box and perform search, then keep Find control on the page
> 4. Click other tab page
> 5. Click result tab page, VSC will quit unexpectedly

Reported to https://github.com/microsoft/vscode/issues/201478

**Comment by scnwwu** [comment]
The bug of VS Code has been fixed. Please move on testing on latest VS Code (1.95). Thanks.

**Comment by Zhirong2022** [comment]
The feature works as expected.  The user can open find dialog on result page and do some search.

**Review by Zhirong2022 — APPROVED** [review]

**Pull request merged**
